# 1 TRAINABLE LAYER ; FasterRcnnMobileNetV3Large320Fpn
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 4 -m FasterRcnnMobileNetV3Large320Fpn -a=crop,distort,flip -tl=1 > ./logs/FasterRcnnMobileNetV3Large320Fpn_layers-1_crop_distort_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 4 -m FasterRcnnMobileNetV3Large320Fpn -a=crop,flip -tl=1 > ./logs/FasterRcnnMobileNetV3Large320Fpn_layers-1_crop_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 4 -m FasterRcnnMobileNetV3Large320Fpn -a=flip -tl=1 > ./logs/FasterRcnnMobileNetV3Large320Fpn_layers-1_flip.txt

# 1 TRAINABLE LAYER ; FasterRcnnMobileNetV3LargeFpn
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 4 -m FasterRcnnMobileNetV3LargeFpn -a=crop,distort,flip -tl=1 > ./logs/FasterRcnnMobileNetV3LargeFpn_layers-1_crop_distort_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 4 -m FasterRcnnMobileNetV3LargeFpn -a=crop,flip -tl=1 > ./logs/FasterRcnnMobileNetV3LargeFpn_layers-1_crop_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 4 -m FasterRcnnMobileNetV3LargeFpn -a=flip -tl=1 > ./logs/FasterRcnnMobileNetV3LargeFpn_layers-1_flip.txt

# 2 TRAINABLE LAYERS ; FasterRcnnMobileNetV3Large320Fpn
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 8 -m FasterRcnnMobileNetV3Large320Fpn -a=crop,distort,flip -tl=2 -lr=5e-4 > ./logs/FasterRcnnMobileNetV3Large320Fpn_layers-2_crop_distort_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 8 -m FasterRcnnMobileNetV3Large320Fpn -a=crop,flip -tl=2 -lr=5e-4 > ./logs/FasterRcnnMobileNetV3Large320Fpn_layers-2_crop_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 8 -m FasterRcnnMobileNetV3Large320Fpn -a=flip -tl=2 -lr=5e-4 > ./logs/FasterRcnnMobileNetV3Large320Fpn_layers-2_flip.txt

# 2 TRAINABLE LAYERS ; FasterRcnnMobileNetV3LargeFpn
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 8 -m FasterRcnnMobileNetV3LargeFpn -a=crop,distort,flip -tl=2 -lr=5e-4 > ./logs/FasterRcnnMobileNetV3LargeFpn_layers-2_crop_distort_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 8 -m FasterRcnnMobileNetV3LargeFpn -a=crop,flip -tl=2 -lr=5e-4 > ./logs/FasterRcnnMobileNetV3LargeFpn_layers-2_crop_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 8 -m FasterRcnnMobileNetV3LargeFpn -a=flip -tl=2 -lr=5e-4 > ./logs/FasterRcnnMobileNetV3LargeFpn_layers-2_flip.txt

# 1 TRAINABLE LAYER ; FasterRcnnResnet50FpnV2
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m FasterRcnnResnet50FpnV2 -a=crop,distort,flip -tl=1 > ./logs/FasterRcnnResnet50FpnV2_layers-1_crop_distort_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m FasterRcnnResnet50FpnV2 -a=crop,flip -tl=1 > ./logs/FasterRcnnResnet50FpnV2_layers-1_crop_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m FasterRcnnResnet50FpnV2 -a=flip -tl=1 > ./logs/FasterRcnnResnet50FpnV2_layers-1_flip.txt

# 2 TRAINABLE LAYERS ; FasterRcnnResnet50FpnV2
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m FasterRcnnResnet50FpnV2 -a=crop,distort,flip -tl=2 > ./logs/FasterRcnnResnet50FpnV2_layers-2_crop_distort_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m FasterRcnnResnet50FpnV2 -a=crop,flip -tl=2 > ./logs/FasterRcnnResnet50FpnV2_layers-2_crop_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m FasterRcnnResnet50FpnV2 -a=flip -tl=2 > ./logs/FasterRcnnResnet50FpnV2_layers-2_flip.txt

# 1 TRAINABLE LAYER ; RetinaNetResnet50FpnV2
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m RetinaNetResnet50FpnV2 -a=crop,distort,flip -tl=1 > ./logs/RetinaNetResnet50FpnV2_layers-1_crop_distort_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m RetinaNetResnet50FpnV2 -a=crop,flip -tl=1 > ./logs/RetinaNetResnet50FpnV2_layers-1_crop_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m RetinaNetResnet50FpnV2 -a=flip -tl=1 > ./logs/RetinaNetResnet50FpnV2_layers-1_flip.txt

# 2 TRAINABLE LAYERS ; RetinaNetResnet50FpnV2
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m RetinaNetResnet50FpnV2 -a=crop,distort,flip -tl=2 > ./logs/RetinaNetResnet50FpnV2_layers-2_crop_distort_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m RetinaNetResnet50FpnV2 -a=crop,flip -tl=2 > ./logs/RetinaNetResnet50FpnV2_layers-2_crop_flip.txt
python train.py ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Day ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Month ../dataset/Data_Annotated_Subset_Object_Detectors/training/Feb_Week ../dataset/Data_Annotated_Subset_Object_Detectors/training/Mar_Week -v ../dataset/Data_Annotated_Subset_Object_Detectors/validation -e 20 -b 2 -m RetinaNetResnet50FpnV2 -a=flip -tl=2 > ./logs/RetinaNetResnet50FpnV2_layers-2_flip.txt
